const RC = require('rc')('QUOTE', require('../../config/default.json'))

module.exports = {
    HOSTNAME: RC.HOSTNAME.replace(/\/$/, ''),
    PORT: RC.PORT,
    HOSTADDRESS: RC.HOSTADDRESS,
    LISTEN_ADDRESS: RC.LISTEN_ADDRESS,
    DATABASE_DIALECT: RC.DATABASE_DIALECT,
    DATABASE_HOST: RC.DATABASE_HOST,
    DATABASE_PORT: RC.DATABASE_PORT,
    DATABASE_USER: RC.DATABASE_USER,
    DATABASE_PASSWORD: RC.DATABASE_PASSWORD,
    DATABASE_SCHEMA: RC.DATABASE_SCHEMA,
    DATABASE_POOL_MINSIZE: RC.DATABASE_POOL_MINSIZE,
    DATABASE_POOL_MAXSIZE: RC.DATABASE_POOL_MAXSIZE
}
