instrumentation:
  include-all-sources: true
  excludes: []
check:
  global:
    statements: 30
    lines: 30
    branches: 17
    functions: 18
#  each:
#    statements: 30
#    lines: 30
#    branches: 17
#    functions: 19
