version: "3.7"
services:
  quoting-service:
      build:
        context: .
        cache_from: 
          - mojaloop/quoting-service
          - quoting-service
      container_name: qs_quoting-service
      links:
        - mysql
        - kafka
      ports:
        - "3002:3002"
      environment:
        - CSL_LOG_TRANSPORT=file