version: "3.7"
services:
  quoting-service:
      build:
        context: .
        cache_from: 
          - mojaloop/quoting-service
          - quoting-service
      container_name: qs_quoting-service
      links:
        - mysql
        - kafka
      ports:
        - "3002:3002"
      # volumes:
      #    - ./docker/central-ledger/default.json:/opt/central-ledger/config/default.json
      # environment:
      #   - CLEDG_DATABASE_URI=mysql://central_ledger:password@mysql:3306/central_ledger
      #   - CLEDG_SIDECAR__DISABLED=true