version: "3.7"
services:
  quoting-service:
      build:
        context: .
        cache_from: 
          - mojaloop/quoting-service
          - quoting-service
      container_name: qs_quoting-service
      ports:
        - "3002:3002"
      volumes:
       - ./docker/quoting-service/default.json:/opt/quoting-service/config/default.json
